// let a = 10;
// ++a;
// document.write(`${a}`);
// let a = 11;
// a++;
// console.log(a);
// let a = 12;
// --a;
// console.log(a);
// let a = 11;
// a--;
// console.log(a);
// var a = 2;
// var b = 1;
// var result = --a - --b + ++b + b--;
// console.log(result);
// var a = 2;
// --a;
// console.log(a);
// var a = 2;
// var b = 1;
// var result = --a - --b;
// console.log(result);
// var a = 2;
// var b = 1;
// let result = --a - --b + ++b;
// console.log(result);
// var a = 2;
// var b = 1;
// result = --a - --b + ++b + b--;
// console.log(result);
